apiVersion: v1
kind: Secret
metadata:
  name: credenciales-manifest
type: Opaque
data:
  username: YWRtaW4=
<<<<<<< HEAD
  password: aG9sYXF1ZXRhbAo=
=======
  password: MTIzNTZhYmNkIAo=
>>>>>>> b2ac7917204d583087b763c494c204eddbab4f8b
